### ISSUE TITLE
Are containers suppose to be repaired?

### ISSUE THREAD

**Issue by BringerOD** [cyberblast/screeps.behaviour-action-pattern#129] opened 2016-09-09 18:08 UTC
Mine keep disappearing and don't get repaired.

**Comment by cyberblast** [comment] 2016-09-09 18:49
Hm thats bad, should get repaired. 
This problem seems to be ocurring. Unfortunately not in my rooms :/ so it's hard to find out what the problem is. 
Are you running the latest version? I already tried to find something and applied some cleanup where the problem could be. So please make sure it's not happening with the latest version. 
May also be a problem when there are far too many decayables. 
Do you have a tower? Should also be no problem if not, but it's different cases - just for further analysis.

**Comment by BringerOD** [comment] 2016-09-09 19:31
I do have a tower.  Maybe your rooms are not having this issues because the tower is not working very hard anymore.  

Maybe there is a way to prioritize containers.

I can try an debug it as well.  It's a tough one because the event only happens once a day.

**Comment by BringerOD** [comment] 2016-09-09 20:20
Seems to be repairing now.

**Comment by cyberblast** [comment] 2016-09-09 20:29
Great! :)

**Comment by BringerOD** [comment] 2016-09-09 21:26
OK, happened again.  I think I know the issue.  Its because of how much the containers drop in health per decay tick compared to other things, i.e. roads.  

I think we need to have a different setting for containers, and maybe other structures that reduce there health at a larger rate during decay.

So the current urgent setting of 1000 is not enough time to catch it before it decays completely if a hauler does not get there in time to refuel the tower.  

Hope that makes sense.

Maybe add a multiplier or factor for different structures based on there health decay rate.

If I set the urgent to 5000, then the roads are constantly being updated, so that is not an option.

**Comment by BringerOD** [comment] 2016-09-09 21:44
Here is a quick fix I made to the rooms section "urgentRepairableSites".

I added to the filter equation to test if its a container than multiply the limit by 10.

` var isUrgent = site => site.hits < LIMIT_URGENT_REPAIRING || (site.structureType === 'container' && site.hits < LIMIT_URGENT_REPAIRING * 10);
`

**Comment by cyberblast** [comment] 2016-09-09 22:16
Well done! :+1: 
Implemented, commited & merged. 
Thank a lot!

**Comment by BringerOD** [comment] 2016-09-09 22:18
No problem!

I updated my comment to a make the multiplier 10 or just set the number to 15001.

Also, the hauler behaviors should only refuel if it has energy, not always.

**Comment by cyberblast** [comment] 2016-09-09 22:36
Yes, that will be checked. In isValidAction. But may nevertheless be added here for clarification & less checks. 
I'm unsure about hard coding the container threshold. I think it should stay relative. If one wants to repair soon, thats why he increased LIMIT_URGENT_REPAIRING, and vice versa. 

default is 1k, your proposal 15k. I'm going to set the (default) multiplicator to 15, ok?

**Comment by BringerOD** [comment] 2016-09-09 22:48
Sounds good.

> (hm, could also be put into a formula regarding hitloss per decay & decay interval, and applied to all decayables. but I think it's ok for the moment...)

Exactly!

I like the way you think!

**Comment by cyberblast** [comment] 2016-09-09 23:07
Thank you! I'm just thinking ;) 
Its a pleasure to work with you! 

I'm going to close this one. And open a reminder task for a later milestone.

**Closed by cyberblast** 2016-09-09 23:07 UTC
Labels: bug, Code ready for validation
